### ISSUE TITLE
This extension is not installable on any currently installed products.

### ISSUE THREAD

**Issue by oleksandrp1** [emtecinc/JMeter-Test-Runner#2]
Visual Studio 2022

20.03.2022 1:24:48 - Microsoft VSIX Installer
20.03.2022 1:24:48 - -------------------------------------------
20.03.2022 1:24:48 - vsixinstaller.exe version:
20.03.2022 1:24:48 - 17.2.37-preview1
20.03.2022 1:24:48 - -------------------------------------------
20.03.2022 1:24:48 - Command line parameters:
20.03.2022 1:24:48 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\...\Downloads\JMeterTestExplorer.Setup.vsix
20.03.2022 1:24:48 - -------------------------------------------
20.03.2022 1:24:48 - Microsoft VSIX Installer
20.03.2022 1:24:48 - -------------------------------------------
20.03.2022 1:24:49 - Initializing Install...
20.03.2022 1:24:50 - Extension Details...
20.03.2022 1:24:50 - 	Identifier         : JMeterTestExplorer.11c0fc08-16c8-4385-9677-4aea2a80f673
20.03.2022 1:24:50 - 	Name               : JMeter Test Explorer
20.03.2022 1:24:50 - 	Author             : Emtec Inc
20.03.2022 1:24:50 - 	Version            : 1.0.1
20.03.2022 1:24:50 - 	Description        : JMeter Test Explorer for testing and publishing Performance and Load Testing result
20.03.2022 1:24:50 - 	Locale             : en-US
20.03.2022 1:24:50 - 	MoreInfoURL        : 
20.03.2022 1:24:50 - 	InstalledByMSI     : False
20.03.2022 1:24:50 - 	SupportedFrameworkVersionRange : [4.5,)
20.03.2022 1:24:50 - 
20.03.2022 1:24:50 - 	SignatureState     : InvalidCertificate
20.03.2022 1:24:50 - 	SignedBy           : Emtec Inc
20.03.2022 1:24:50 - 	Certificate Info   : 
20.03.2022 1:24:50 - 		-------------------------------------------------------
20.03.2022 1:24:50 - 		[Subject]       : CN=Emtec Inc, O=Emtec Inc, STREET=1 S Wacker Dr Suite 1680, L=Chicago, S=IL, PostalCode=60606, C=US
20.03.2022 1:24:50 - 		[Issuer]        : CN=Sectigo RSA Code Signing CA, O=Sectigo Limited, L=Salford, S=Greater Manchester, C=GB
20.03.2022 1:24:50 - 		[Serial Number] : 4D49B0A965A51D805D0E5507EF02A9BA
20.03.2022 1:24:50 - 		[Not Before]    : 28.03.2019 2:00:00
20.03.2022 1:24:50 - 		[Not After]     : 28.03.2020 1:59:59
20.03.2022 1:24:50 - 		[Thumbprint]    : FF7456EFF20BBA08EA61296D9302E6CDBD073B7E
20.03.2022 1:24:50 - 
20.03.2022 1:24:50 - 	Supported Products : 
20.03.2022 1:24:50 - 		Microsoft.VisualStudio.Community
20.03.2022 1:24:50 - 			Version : [14.0,17.0)
20.03.2022 1:24:50 - 			ProductArchitecture : x86
20.03.2022 1:24:50 - 
20.03.2022 1:24:50 - 	References         : 
20.03.2022 1:24:50 - 	Prerequisites      : 
20.03.2022 1:24:50 - 		-------------------------------------------------------
20.03.2022 1:24:50 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
20.03.2022 1:24:50 - 		Name         : Visual Studio core editor
20.03.2022 1:24:50 - 		Version      : [15.0.25904.2,)
20.03.2022 1:24:50 - 
20.03.2022 1:24:50 - Signature Details...
20.03.2022 1:24:50 - 	Extension is signed with an invalid certificate
20.03.2022 1:24:50 - 		(NotTimeValid)      : A required certificate is not within its validity period when verifying against the current system clock or the timestamp in the signed file.
20.03.2022 1:24:50 - 
20.03.2022 1:24:50 - 
20.03.2022 1:24:50 - Searching for applicable products...
20.03.2022 1:24:50 - Found installed product - Global Location
20.03.2022 1:24:50 - Found installed product - Visual Studio Community 2022
20.03.2022 1:24:50 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by monoculture** [comment]
@oleksandrp1 - possible workaround

Extract the the contents of the VSIX to disk and then edit the file 'extension.vsixmanifest'

Change line 10 from:

InstallationTarget Id="Microsoft.VisualStudio.Community" Version="[14.0,17.0)" 

to:

InstallationTarget Id="Microsoft.VisualStudio.Community" Version="[14.0,18.0)" 

repackage and install.

**Comment by oleksandrp1** [comment]
Thank you! You helped
